language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
cache: pip3
install: "pip3 install numpy pandas requests wbdata"
# command to run tests
script: python3 tests/easy_tests.py